server:
  port: 8080
  readTimout: 10
  writeTimout: 10
  idleTimout: 30
  maxHeaderBytes: 1048576

database:
  host: "database"
  port: 5432
  user: "postgres"
  name: "postgres"
  password: "postgres"
  ssl: "disable"
